@startuml Use Case Online System

title Online Ice Cream Shop System

left to right direction

actor Client as cli
actor Manager as mana


rectangle Sorveteria {
    cli --> (Browse Products)
    cli --> (Buy Products) 
    cli --> (Purchase History)
    cli --> (Manage Account)
    cli --> (Track Order)

    mana --> (Generate Reports)
    mana --> (Manage Products)
    mana --> (Manage Orders)
}





@enduml